[package]
name = "bevy_spine"
version = "0.7.0"
edition = "2021"
description = "Spine plugin for Bevy utilizing rusty_spine"
homepage = "https://github.com/jabuwu/bevy_spine"
repository = "https://github.com/jabuwu/bevy_spine"
readme = "readme.md"
license-file = "LICENSE"
exclude = [
    "assets/*",
]

[dependencies]
rusty_spine = { git = "https://github.com/dt665m/rusty_spine.git", branch = "dark_color_pma-opt" }

bevy = { version = "0.12", default-features = false, features = [ "bevy_render", "bevy_asset", "bevy_sprite" ] }
glam = { version = "0.24", features = [ "mint" ] }
thiserror = "1.0.50"

[dev-dependencies]
lerp = "0.4"
bevy = { version = "0.12", default-features = true }

[workspace]
resolver = "2"
members = [
    "ci"
]
