[package]
name = "bevy_spine"
version = "0.8.0"
edition = "2021"
description = "Spine plugin for Bevy utilizing rusty_spine"
homepage = "https://github.com/jabuwu/bevy_spine"
repository = "https://github.com/jabuwu/bevy_spine"
readme = "readme.md"
license-file = "LICENSE"
exclude = ["assets/*"]

[dependencies]
# rusty_spine = "0.7"
log = "0.4.0" 
rusty_spine = { git = "https://github.com/jabuwu/rusty_spine", rev = "refs/pull/24/head" }
bevy = { version = "0.13", default-features = false, features = [
    "bevy_render",
    "bevy_asset",
    "bevy_sprite",
] }
glam = { version = "0.25", features = ["mint"] }
thiserror = "1.0.50"

[dev-dependencies]
lerp = "0.5"
bevy = { version = "0.13", default-features = true }

[workspace]
resolver = "2"
members = ["ci"]
